### ISSUE TITLE
Should we skip this for Python>=3.5?

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/typing-feedstock#9]
Ping @msarahan, @ocefpaf ..

I am experimenting with python 3.7 and noticed this got built. I don't think we want this?

**Comment by ocefpaf** [comment]
As far as I know installing this in Python 3.6 and above is harmless and the `stdlib` will be used instead. I guess that people like to be able to install it everywhere to  simplify CIs configurations, etc.

**Comment by mingwandroid** [comment]
Is rather it were skipped personally.

There risk of having both: machines finding the wrong one (because someone messed with sys.path), tooling finding the wrong one (because they implement their own path search) and humans finding the wrong one because they found the wrong one.

**Comment by ocefpaf** [comment]
The docs do say:

    NOTE: in Python 3.5 and later, the typing module lives in the stdlib,
    and installing this package has NO EFFECT.

but I guess users can always find a way to circunvent that and shoot themselves in the foot.

I'd be OK not building that for Python >=3.6 but I'm not a heavy user of typing to say that the advantages are worth the disadvantages. @msarahan what do you think?

**Comment by msarahan** [comment]
also not a typing user, but I think in other cases like this, we'd expect it to be a dep with a selector like [py<36].  Better to not build it and force correct recipes than risk confusion.
